Repository alinebastos/free-courses, pull requests merged in 2020-10, with the labels that each got.

#18 New links
  README.md
Labels: waiting fix

#24 adds links
  README.md
Labels: waiting fix

#28 New courses added
  README.md
Labels: waiting fix

#26 Mini curso de TypeScript
  README.md
Labels: waiting fix

#30 Cursos da Rocketseat organizados de acordo com a categoria
  README.md
Labels: hacktoberfest-accepted

#54 Adicionado 3 cursos
  README.md
Labels: hacktoberfest-accepted, waiting fix

#56 adiconando cursos gratis da Harvard, Microsoft, AI e css/ html de um …
  README.md
Labels: hacktoberfest-accepted

#57 Adicionado trilhas sp tech
  README.md
Labels: hacktoberfest-accepted

#59 Adição de cursos relacionados a aprendizado profundo
  README.md
Labels: hacktoberfest-accepted

#60 Update README.md
  README.md
Labels: hacktoberfest-accepted

#61 Add Curso de Big Data
  README.md
Labels: hacktoberfest-accepted

#64 Adding Node.Js course
  README.md
Labels: hacktoberfest-accepted
